In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.datasets import load_wine
from sklearn import  metrics

## Question 1

In [2]:
data = load_wine()

In [3]:
x = data.data
y = data.target

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.25)

In [5]:
X_train.shape , X_test.shape

((133L, 13L), (45L, 13L))

## Question 2

In [6]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [7]:
bagging = BaggingClassifier(base_estimator=model,max_samples=0.5,max_features=0.5)

In [8]:
bagging.fit(X_train,Y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=0.5,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [9]:
pred = bagging.predict(X_test)

In [10]:
metrics.accuracy_score(Y_test,pred)

0.9777777777777777

In [11]:
print(metrics.classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        15
          1       1.00      1.00      1.00        21
          2       1.00      0.89      0.94         9

avg / total       0.98      0.98      0.98        45



In [12]:
print(metrics.confusion_matrix(Y_test,pred))

[[15  0  0]
 [ 0 21  0]
 [ 1  0  8]]


In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
model1 = RandomForestClassifier(criterion="entropy",max_leaf_nodes=40)
model1.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=40,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [15]:
model1_pred1 = model1.predict(X_test)

In [16]:
metrics.accuracy_score(Y_test,model1_pred1)

1.0

In [17]:
print(metrics.classification_report(Y_test,model1_pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        15
          1       1.00      1.00      1.00        21
          2       1.00      1.00      1.00         9

avg / total       1.00      1.00      1.00        45



In [18]:
print(metrics.confusion_matrix(Y_test,model1_pred1))

[[15  0  0]
 [ 0 21  0]
 [ 0  0  9]]


In [19]:
from sklearn.ensemble import GradientBoostingClassifier
model2 = GradientBoostingClassifier(n_estimators=100,learning_rate=1.0,max_depth=1,random_state=5)
model2.fit(X_train,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=1.0, loss='deviance', max_depth=1,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=5, subsample=1.0, verbose=0,
              warm_start=False)

In [20]:
pred2 = model2.predict(X_test)

In [21]:
metrics.accuracy_score(Y_test,pred2)

0.9777777777777777

In [22]:
print(metrics.classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        15
          1       1.00      0.95      0.98        21
          2       1.00      1.00      1.00         9

avg / total       0.98      0.98      0.98        45



In [23]:
print(metrics.confusion_matrix(Y_test,pred2))

[[15  0  0]
 [ 1 20  0]
 [ 0  0  9]]


In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC

In [25]:
model3 = DecisionTreeClassifier()
model4 = LogisticRegression()
model5 = SVC()

In [26]:
final_model = VotingClassifier(estimators=[('DT',model3),('LR',model4),('SVC',model5)])

In [27]:
final_model.fit(X_train,Y_train)

VotingClassifier(estimators=[('DT', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [28]:
pred_final = final_model.predict(X_test)

C:\Users\Acer\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [29]:
metrics.accuracy_score(Y_test,pred_final)

0.9555555555555556

In [30]:
print(metrics.classification_report(Y_test,pred_final))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        15
          1       1.00      0.95      0.98        21
          2       0.89      0.89      0.89         9

avg / total       0.96      0.96      0.96        45



In [31]:
print(metrics.confusion_matrix(Y_test,pred_final))

[[15  0  0]
 [ 0 20  1]
 [ 1  0  8]]
