## Question 1

In [71]:
s = 5.0/14     ## prob of sunny
y = 9.0/14     ## prob of yes
z = 3.0/9      ## prob of (sunny/yes)
x = (z*y)/s    ## prob of (yes/sunny)
x

0.6

In [72]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets

## Question 2

In [73]:
df = datasets.load_iris()
df

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [74]:
x = df.data
y = df.target

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_train.shape , x_test.shape

((105L, 4L), (45L, 4L))

In [76]:
model = GaussianNB()
model.fit(x,y)

GaussianNB(priors=None)

In [77]:
pred = model.predict(x)
metrics.accuracy_score(y,pred)*100

96.0

In [78]:
from sklearn.metrics import classification_report
print(classification_report(y,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150



In [79]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y,pred))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [80]:
from sklearn.naive_bayes import MultinomialNB

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_train.shape , x_test.shape

((105L, 4L), (45L, 4L))

In [82]:
model1 = MultinomialNB()
model1.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [83]:
pred1 = model1.predict(x)
metrics.accuracy_score(y,pred1)*100

95.33333333333334

In [84]:
from sklearn.metrics import classification_report
print(classification_report(y,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.92      0.93        50
          2       0.92      0.94      0.93        50

avg / total       0.95      0.95      0.95       150



In [85]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y,pred1))

[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]
