In [382]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.svm import SVC
%matplotlib inline

## Question 1

In [383]:
digit = load_digits()
x=digit.data
y=digit.target

In [384]:
x.shape , y.shape

((1797L, 64L), (1797L,))

## Question 2

In [460]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3)

## Question 3

## a.Linear

In [461]:
model1 = SVC(C=1.1,kernel = 'linear')

In [462]:
model1.fit(X_train,Y_train)

SVC(C=1.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [463]:
pred1 = model1.predict(X_test)

In [464]:
print(metrics.classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        60
          1       0.93      1.00      0.96        52
          2       1.00      1.00      1.00        56
          3       1.00      0.96      0.98        56
          4       1.00      1.00      1.00        52
          5       1.00      1.00      1.00        56
          6       1.00      1.00      1.00        58
          7       1.00      1.00      1.00        55
          8       0.98      0.91      0.94        44
          9       0.98      1.00      0.99        51

avg / total       0.99      0.99      0.99       540



In [465]:
metrics.accuracy_score(Y_test,pred1)*100

98.88888888888889

In [466]:
print(metrics.confusion_matrix(Y_test,pred1))

[[60  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 0  0 56  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  0  0  0  1  1]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0  0 56  0  0  0  0]
 [ 0  0  0  0  0  0 58  0  0  0]
 [ 0  0  0  0  0  0  0 55  0  0]
 [ 0  4  0  0  0  0  0  0 40  0]
 [ 0  0  0  0  0  0  0  0  0 51]]


## b.Poly

In [467]:
model2 = SVC(C=1.1,kernel='poly')

In [468]:
model2.fit(X_train,Y_train)

SVC(C=1.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [469]:
pred2 = model2.predict(X_test)

In [470]:
print(metrics.classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        60
          1       0.98      1.00      0.99        52
          2       1.00      1.00      1.00        56
          3       1.00      0.98      0.99        56
          4       1.00      1.00      1.00        52
          5       1.00      1.00      1.00        56
          6       1.00      0.98      0.99        58
          7       1.00      1.00      1.00        55
          8       0.96      0.98      0.97        44
          9       1.00      1.00      1.00        51

avg / total       0.99      0.99      0.99       540



In [471]:
metrics.accuracy_score(Y_test,pred2)*100

99.44444444444444

In [472]:
print(metrics.confusion_matrix(Y_test,pred2))

[[60  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 0  0 56  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  1  0]
 [ 0  0  0  0 52  0  0  0  0  0]
 [ 0  0  0  0  0 56  0  0  0  0]
 [ 0  0  0  0  0  0 57  0  1  0]
 [ 0  0  0  0  0  0  0 55  0  0]
 [ 0  1  0  0  0  0  0  0 43  0]
 [ 0  0  0  0  0  0  0  0  0 51]]


## c.Gaussian

In [473]:
model3 = SVC(C=1.1,kernel='rbf')

In [474]:
model3.fit(X_train,Y_train)

SVC(C=1.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [475]:
pred3 = model3.predict(X_test)

In [476]:
print(metrics.classification_report(Y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.45      0.62        60
          1       1.00      0.31      0.47        52
          2       1.00      0.25      0.40        56
          3       1.00      0.41      0.58        56
          4       1.00      0.60      0.75        52
          5       1.00      0.45      0.62        56
          6       1.00      0.43      0.60        58
          7       1.00      0.49      0.66        55
          8       0.14      1.00      0.24        44
          9       1.00      0.55      0.71        51

avg / total       0.93      0.48      0.57       540



In [477]:
metrics.accuracy_score(Y_test,pred3)*100

48.148148148148145

In [478]:
print(metrics.confusion_matrix(Y_test,pred3))

[[27  0  0  0  0  0  0  0 33  0]
 [ 0 16  0  0  0  0  0  0 36  0]
 [ 0  0 14  0  0  0  0  0 42  0]
 [ 0  0  0 23  0  0  0  0 33  0]
 [ 0  0  0  0 31  0  0  0 21  0]
 [ 0  0  0  0  0 25  0  0 31  0]
 [ 0  0  0  0  0  0 25  0 33  0]
 [ 0  0  0  0  0  0  0 27 28  0]
 [ 0  0  0  0  0  0  0  0 44  0]
 [ 0  0  0  0  0  0  0  0 23 28]]


## d.Sigmoid

In [479]:
model4 = SVC(C=1.1,kernel = 'sigmoid')

In [480]:
model4.fit(X_train,Y_train)

SVC(C=1.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [481]:
pred4 = model4.predict(X_test)

In [482]:
print(metrics.classification_report(Y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        60
          1       0.10      1.00      0.19        52
          2       0.00      0.00      0.00        56
          3       0.00      0.00      0.00        56
          4       0.00      0.00      0.00        52
          5       0.00      0.00      0.00        56
          6       0.00      0.00      0.00        58
          7       0.00      0.00      0.00        55
          8       0.00      0.00      0.00        44
          9       0.00      0.00      0.00        51

avg / total       0.01      0.10      0.02       540



In [483]:
metrics.accuracy_score(Y_test,pred4)*100

9.62962962962963

In [484]:
print(metrics.confusion_matrix(Y_test,pred4))

[[ 0 37  0  0  0  0  0  0 23  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  1  0]
 [ 0 56  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  9  0]
 [ 0 57  0  0  0  0  0  0  1  0]
 [ 0 54  0  0  0  0  0  0  1  0]
 [ 0 44  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  1  0]]
