In [269]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.model_selection import train_test_split

## Question 1

In [270]:
digit = load_digits()
x=digit.data
y=digit.target

In [271]:
x.shape , y.shape

((1797L, 64L), (1797L,))

## Question 2

In [272]:
x = preprocessing.scale(x)
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [273]:
df = pd.DataFrame(x)
df.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

## Question 4

In [274]:
from sklearn.decomposition import PCA
pca = PCA(n_components=16)
principalComponents = pca.fit_transform(x)
principalComponents

array([[ 1.91419517, -0.95449584, -3.94601814, ..., -0.19592926,
         0.8394834 , -0.10743151],
       [ 0.58900087,  0.92460715,  3.92465948, ..., -0.37673076,
        -0.74333179,  0.19935689],
       [ 1.30205821, -0.31718045,  3.02336492, ..., -0.98405067,
        -1.17092507, -0.38692195],
       ...,
       [ 1.02259632, -0.14791691,  2.46993398, ...,  0.2480451 ,
         0.35349145, -1.20365723],
       [ 1.07605196, -0.3809408 , -2.45555659, ..., -0.76537443,
         0.07190875, -0.17160136],
       [-1.25770552, -2.22766117,  0.28362934, ...,  0.7523016 ,
         1.87440668, -0.21926673]])

In [275]:
#principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])

In [276]:
#principalDf

In [277]:
x = principalComponents
x.shape , y.shape

((1797L, 16L), (1797L,))

## Question 3

In [278]:
from sklearn.linear_model import LogisticRegression
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.3)

## Question 5

In [279]:
reg = LogisticRegression()
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [280]:
pred = reg.predict(X_test)

## Question 6

In [281]:
metrics.accuracy_score(Y_test,pred)*100

94.81481481481482

In [282]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        51
          1       0.90      0.96      0.93        54
          2       0.93      0.98      0.95        42
          3       1.00      0.88      0.93        65
          4       1.00      0.94      0.97        52
          5       0.95      0.95      0.95        65
          6       0.98      0.96      0.97        51
          7       0.95      1.00      0.97        53
          8       0.92      0.87      0.90        54
          9       0.86      0.96      0.91        53

avg / total       0.95      0.95      0.95       540



In [283]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,pred))

[[51  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  0  0  0  0  0  1  1]
 [ 0  0 41  0  0  0  1  0  0  0]
 [ 0  0  2 57  0  1  0  3  1  1]
 [ 0  0  0  0 49  0  0  0  0  3]
 [ 0  0  0  0  0 62  0  0  0  3]
 [ 0  0  0  0  0  0 49  0  2  0]
 [ 0  0  0  0  0  0  0 53  0  0]
 [ 0  5  1  0  0  1  0  0 47  0]
 [ 0  1  0  0  0  1  0  0  0 51]]
